"""Add Pickup Requests table

Revision ID: 3_add_pickup_requests
Revises: 2_add_items_categories
Create Date: 2026-03-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3_add_pickup_requests'
down_revision: Union[str, None] = '2_add_items_categories'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'ASSIGNED', 'IN_TRANSIT', 'PICKED_UP', 'COMPLETED', 'CANCELED', name='pickupstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('pickup_address', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_requests_agent_id'), 'pickup_requests', ['agent_id'], unique=False)
    op.create_index(op.f('ix_pickup_requests_item_id'), 'pickup_requests', ['item_id'], unique=True)
    op.create_index(op.f('ix_pickup_requests_user_id'), 'pickup_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_pickup_requests_id'), 'pickup_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pickup_requests_id'), table_name='pickup_requests')
    op.drop_index(op.f('ix_pickup_requests_user_id'), table_name='pickup_requests')
    op.drop_index(op.f('ix_pickup_requests_item_id'), table_name='pickup_requests')
    op.drop_index(op.f('ix_pickup_requests_agent_id'), table_name='pickup_requests')
    op.drop_table('pickup_requests')
    # ### end Alembic commands ###
