"""Add Processing Centers table

Revision ID: 4_add_processing_centers
Revises: 3_add_pickup_requests
Create Date: 2026-03-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4_add_processing_centers'
down_revision: Union[str, None] = '3_add_pickup_requests'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('center_type', sa.Enum('RECYCLING', 'REPAIR', name='centertype'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_centers_id'), 'processing_centers', ['id'], unique=False)
    op.create_index(op.f('ix_processing_centers_user_id'), 'processing_centers', ['user_id'], unique=True)
    
    op.add_column('items', sa.Column('assigned_center_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_items_assigned_center_id'), 'items', ['assigned_center_id'], unique=False)
    op.create_foreign_key(None, 'items', 'processing_centers', ['assigned_center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_assigned_center_id'), table_name='items')
    op.drop_column('items', 'assigned_center_id')
    
    op.drop_index(op.f('ix_processing_centers_user_id'), table_name='processing_centers')
    op.drop_index(op.f('ix_processing_centers_id'), table_name='processing_centers')
    op.drop_table('processing_centers')
    # ### end Alembic commands ###
