"""Add ItemProcessing table

Revision ID: 5_add_processing
Revises: 4_add_processing_centers
Create Date: 2026-03-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5_add_processing'
down_revision: Union[str, None] = '4_add_processing_centers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_processing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('process_type', sa.Enum('RECYCLING', 'REPAIR', 'DONATION', name='processtype'), nullable=False),
    sa.Column('final_status', sa.Enum('RECYCLED', 'REPAIRED', 'DONATED', 'SCRAPPED', 'RETURNED', name='finalstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('process_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['processing_centers.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_processing_center_id'), 'item_processing', ['center_id'], unique=False)
    op.create_index(op.f('ix_item_processing_id'), 'item_processing', ['id'], unique=False)
    op.create_index(op.f('ix_item_processing_item_id'), 'item_processing', ['item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_processing_item_id'), table_name='item_processing')
    op.drop_index(op.f('ix_item_processing_id'), table_name='item_processing')
    op.drop_index(op.f('ix_item_processing_center_id'), table_name='item_processing')
    op.drop_table('item_processing')
    # ### end Alembic commands ###
