import enum

class Role(str, enum.Enum):
    ADMIN = "ADMIN"
    USER = "USER"
    PICKUP_AGENT = "PICKUP_AGENT"
    RECYCLING_CENTER = "RECYCLING_CENTER"
    REPAIR_CENTER = "REPAIR_CENTER"

class ItemCondition(str, enum.Enum):
    WORKING = "WORKING"
    REPAIRABLE = "REPAIRABLE"
    NON_WORKING = "NON_WORKING"
    SCRAP = "SCRAP"

class ItemStatus(str, enum.Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    READY_FOR_PICKUP = "READY_FOR_PICKUP"
    PICKUP_REQUESTED = "PICKUP_REQUESTED"
    PICKED_UP = "PICKED_UP"
    ASSIGNED_TO_CENTER = "ASSIGNED_TO_CENTER"
    IN_PROCESSING = "IN_PROCESSING"
    COMPLETED = "COMPLETED"

class PickupStatus(str, enum.Enum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    ASSIGNED = "ASSIGNED"
    IN_TRANSIT = "IN_TRANSIT"
    PICKED_UP = "PICKED_UP"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"

class ProcessType(str, enum.Enum):
    RECYCLING = "RECYCLING"
    REPAIR = "REPAIR"
    DONATION = "DONATION"

class FinalStatus(str, enum.Enum):
    RECYCLED = "RECYCLED"
    REPAIRED = "REPAIRED"
    DONATED = "DONATED"
    SCRAPPED = "SCRAPPED"
    RETURNED = "RETURNED"

class CenterType(str, enum.Enum):
    RECYCLING = "RECYCLING"
    REPAIR = "REPAIR"
